export const FETCH_INGREDIENTS_START = 'FETCH_INGREDIENTS_START';
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL';

export const FETCH_DRINK_MENU_START = 'FETCH_DRINK_MENU_START';
export const FETCH_DRINK_MENU_SUCCESS = 'FETCH_DRINK_MENU_SUCCESS';
export const FETCH_DRINK_MENU_FAIL = 'FETCH_DRINK_MENU_FAIL';

export const ADD_BURGER = 'ADD_BURGER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const RESET_DRINK_ORDER = 'RESET_DRINK_ORDER';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const ADD_ONE = 'ADD_ONE';
export const SUBTRACT_ONE = 'SUBTRACT_ONE';
export const RESET_ORDER = 'RESET_ORDER';

export const COPY_BURGER_ORDER_INGREDIENTS =
  'COPY_BURGER_ORDER_INGREDIENTS';
export const ADD_BURGER_ORDER_INGREDIENTS =
  'ADD_BURGER_ORDER_INGREDIENTS';
export const REDUCE_BURGER_ORDER_INGREDIENTS =
  'REDUCE_BURGER_ORDER_INGREDIENTS';
export const RESET_BURGER_ORDER = 'RESET_BURGER_ORDER';

export const SUBMIT_ORDER_START = 'SUBMIT_ORDER_START';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';
export const SUBMIT_ORDER_FAIL = 'SUBMIT_ORDER_FAILT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_ORDER_HISTORY_START = 'FETCH_ORDER_HISTORY_START';
export const FETCH_ORDER_HISTORY_SUCCESS =
  'FETCH_ORDER_HISTORY_SUCCESS';
export const FETCH_ORDER_HISTORY_FAIL = 'FETCH_ORDER_HISTORY_FAIL';
